'use strict';

// Promise is a JavaScript object for asynchronous operation.
// State: pending -> fulfilled or rejected
// Producer vs Consumer

// 1. Producer
// when new Promise is created, the executor runs automatically.
const promise = new Promise((resolve, reject) => {
    // doing some heavy work (network, read files)
    console.log('doing something...');
    setTimeout(() => {
        resolve('ellie');
        // reject(new Error('no network'));
    }, 2000);
});

// 2. Consumers: then, catch, finally
// then: promiseÍ∞Ä Ï†ïÏÉÅÏ†ÅÏúºÎ°ú ÏàòÌñâÎêòÏñ¥ÏÑú resolve ÏΩúÎ∞±Ìï®ÏàòÎ°ú Ï†ÑÎã¨Îêú Í∞íÏù¥ valueÎ°ú Ï†ÑÎã¨Îê®
// catch: promiseÍ∞Ä Ï†ïÏÉÅÏ†ÅÏúºÎ°ú ÏàòÌñâÎêòÏßÄ ÏïäÏïÑÏÑú reject ÏΩúÎ∞±Ìï®ÏàòÎ°ú Ï†ÑÎã¨Îêú Í∞íÏù¥ errorÎ°ú Ï†ÑÎã¨Îê®
// finally: ÏÑ±Í≥µÌïòÎì† Ïã§Ìå®ÌïòÎì† ÎßàÏßÄÎßâÏóê Î¨¥Ï°∞Í±¥ Ïã§ÌñâÎê®
promise
    .then((value) => {
        console.log(value);
    })
    .catch(error => {
        console.log(error);
    })
    .finally(() => console.log('finally'));

// 3. Promise chaining
// thenÏùÄ Í∞íÏùÑ Î∞îÎ°ú Ï†ÑÎã¨Ìï† ÏàòÎèÑ ÏûàÍ≥†, PromiseÎ•º Ï†ÑÎã¨Ìï† ÏàòÎèÑ ÏûàÎã§.
const fetchNumber = new Promise((resolve, reject) => {
    setTimeout(() => resolve(1), 1000);
});


fetchNumber
    .then(num => num * 2) // 1
    .then(num => num * 3) // 2
    .then(num => {
        return new Promise((resolve, reject) => {
            setTimeout(() => resolve(num - 1), 1000); // 3
        });
    })
    .then(num => console.log(num)); // 4

// 4. Error Handling
const getHen = () =>
    new Promise((resolve, reject) => {
        setTimeout(() => resolve('üêì'), 1000);
    });
const getEgg = hen =>
    new Promise((resolve, reject) => {
        // setTimeout(() => resolve(`${hen} => ü•ö`), 1000);
        setTimeout(() => reject(new Error(`error! ${hen} => ü•ö`)), 1000);
    });
const cook = egg =>
    new Promise((resolve, reject) => {
        setTimeout(() => resolve(`${egg} => üç≥`), 1000);
    });

// getHen()
//     .then(hen => getEgg(hen))
//     // .then(egg => cook(egg))
//     .then(cook)
//     .then(meal => console.log(meal))
//     .catch(error => console.log(error));

getHen()
    .then(getEgg)
    .catch(error => {
        return 'üçû';
    })
    .then(cook)
    .then(console.log)
    .catch(console.log);

// 5. Callback Hell example



